/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cardboard_box\scene.gltf --transform --types -o .\components\box-model.tsx -k -K -j 
Files: .\cardboard_box\scene.gltf [4.9KB] > D:\Atom\WorkaroundProject\CEDT\Year3Term1\2110575-iot\project-i\safebox\components\scene-transformed.glb [28.79KB] (-488%)
Author: Pricey1600 (https://sketchfab.com/Pricey1600)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cardboard-box-4e622ef1a09c43e28a49d9fa37f9eeee
Title: Cardboard Box
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    CardboardBox_LP_lambert1_0: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./scene-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <mesh
          name='CardboardBox_LP_lambert1_0'
          geometry={nodes.CardboardBox_LP_lambert1_0.geometry}
          material={materials.lambert1}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
